# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-media-plugin-demucs',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-media-plugin-demucs',
                'lib_path': 'cjm_media_plugin_demucs'},
  'syms': {}}
